/*******************************************************************************
 * Copyright (c) 2019 Red Hat, Inc.
 * Distributed under license by Red Hat, Inc. All rights reserved.
 * This program is made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v20.html
 *
 * Contributors:
 * Red Hat, Inc. - initial API and implementation
 ******************************************************************************/
package org.jboss.tools.intellij.openshift.ui.url;

import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.ui.ValidationInfo;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.Dimension;
import java.awt.Insets;
import java.time.temporal.ValueRange;
import java.util.ArrayList;
import java.util.List;

@SuppressWarnings({"java:S1171","java:S100"})
public class CreateURLDialog extends DialogWrapper {
    private JPanel contentPane;
    private JTextField nameTextField;
    private JCheckBox secureCheckBox;
    private JTextField portField;
    private JTextField hostField;
    private JLabel hostLabel;

    /**
     * Constructor for CreateURL dialog.
     *
     * @param showHostField set to @true to show editable hostField.
     */
    public CreateURLDialog(boolean showHostField, String hostValue) {
        super(null, false, IdeModalityType.IDE);
        init();
        setTitle("Create URL");
        portField.setText("1024");
        hostField.setVisible(showHostField);
        hostLabel.setVisible(showHostField);
        if (showHostField) {
            hostField.setText(hostValue);
        }
    }

    private String getPortFieldValue() {
        return portField.getText().trim();
    }

    @NotNull
    @Override
    protected List<ValidationInfo> doValidateAll() {
        List<ValidationInfo> validations = new ArrayList<>();
        if (portField.isVisible()) {
            try {
                Integer value = Integer.valueOf(getPortFieldValue());
                if (!ValueRange.of(1024, 65535).isValidIntValue(value)) {
                    validations.add(new ValidationInfo("Port value must be between 1024 and 65535", portField));
                }
            } catch (NumberFormatException e) {
                validations.add(new ValidationInfo("Port value must be an integer", portField));
            }
        }
        return validations;
    }

    @Nullable
    @Override
    protected JComponent createCenterPanel() {
        return contentPane;
    }

    public String getName() {
        return nameTextField.getText();
    }

    public boolean isSecure() {
        return secureCheckBox.isSelected();
    }

    public Integer getPort() {
        return Integer.valueOf(getPortFieldValue());
    }

    public String getHost() {
        return hostField.getText().trim();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Name");
        contentPane.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTextField = new JTextField();
        contentPane.add(nameTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("Port");
        contentPane.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
