name: check-oc

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:
jobs:
  check-oc-repo:
    runs-on: ubuntu-latest
    env:
      TOOL_REPO: openshift/oc
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      - name: Get latest OC version
        run: |
          echo "REPO_OC_VERSION=$(cat src/main/resources/tools.json | jq -r .tools.oc.version)" >> $GITHUB_ENV
          baseUrl="'https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/release.txt"
          echo "LATEST_TOOL_URL=$(echo ${baseUrl})" >> $GITHUB_ENV
          echo "LATEST_TOOL_RELEASE=$(curl -s -L ${baseUrl} | grep "Name:" | head -n 1 | sed 's|Name:||' | sed 's| ||g')" >> $GITHUB_ENV
      - name: Find existing PR for OC version
        run: |
          echo PR_EXISTS=$(gh pr --repo ${{ github.repository }} list --state open --search "fix: update oc ${{env.LATEST_TOOL_RELEASE}} in:title" --json url | jq length) >> $GITHUB_ENV
      - name: Update tools.json with latest oc version
        if: ${{ (env.LATEST_TOOL_RELEASE != '') && (env.LATEST_TOOL_RELEASE != env.REPO_OC_VERSION) && (env.PR_EXISTS == 0) }}
        run: |
          jq --indent 4 '.tools.oc.version = "${{ env.LATEST_TOOL_RELEASE }}"' src/main/resources/tools.json | jq --indent 4 '.tools.oc.versionMatchRegExpr = "${{ env.LATEST_TOOL_RELEASE }}"' > src/main/resources/tools.json.new
          mv src/main/resources/tools.json.new src/main/resources/tools.json
          for platform in win osx \"osx-aarch64\" lnx \"lnx-arm64\"; do
            old_url=`jq -r .tools.oc.platforms.${platform}.url src/main/resources/tools.json`
            new_url=`echo ${old_url} | sed "s|${{ env.REPO_OC_VERSION }}|${{ env.LATEST_TOOL_RELEASE }}|"`
            checksum_url=`echo "${new_url}.sha256"`
            checksum=`curl -s -L ${checksum_url} | sed "s| ||g"`
            jq --indent 4 ".tools.oc.platforms.${platform}.url = \"${new_url}\"" src/main/resources/tools.json \
              | jq --indent 4 ".tools.oc.platforms.${platform}.sha256sum = \"${checksum}\"" > src/main/resources/tools.json.new
            mv src/main/resources/tools.json.new src/main/resources/tools.json
          done
      - name: Create pull request
        if: ${{ (env.LATEST_TOOL_RELEASE != '') && (env.LATEST_TOOL_RELEASE != env.REPO_OC_VERSION) && (env.PR_EXISTS == 0) }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b "oc-${{ env.LATEST_TOOL_RELEASE }}"
          git commit -am "fix: Update oc to ${{ env.LATEST_TOOL_RELEASE }}"
          git push origin "oc-${{ env.LATEST_TOOL_RELEASE }}"
          gh pr create --title "fix: Update oc to ${{ env.LATEST_TOOL_RELEASE }}" --body "See ${{ env.LATEST_TOOL_URL }}"
